config/routes.rb
Rails.application.routes.draw do
  root "homepages#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: 'users#show'

  get '/admin/dashboard', to: 'admin/dashboards#show'
  get '/admin/bike-shop/new', to: 'admin/items#new'

  resources :users, only: [:new, :create, :edit, :update]

  get "/:station-name", to: redirect("/%{station-name}")
  resources :stations, only: [:index, :show]

  resources :trips, only: [:show, :index]

  resources :items, only: [:show]
  get '/bike-shop', to: 'items#index'

  resources :orders, only: [:new, :create, :show]

  namespace :admin do
    resources :stations, only: [:new, :create, :destroy, :edit, :update]
    resources :trips
    resources :items
    resources :orders, only: [:update]
    get '/bike-shop', to: 'items#index'
    get '/dashboard', to: 'dashboards#show'
  end

  get '/cart', to: "cart#index"
  patch '/bike-shop', to: "cart#update"
  delete '/bike-shop', to: 'cart#destroy'

  get '/stations-dashboard', to: 'homepages#show'
  get '/trips-dashboard', to: 'homepages#show'

  match '*path', to: 'unknowns#index', via: :all
end

app/models/station.rb
class Station < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged]
  has_many :start_stations, class_name: "Trip", foreign_key: "start_station_id"
  has_many :end_stations, class_name: "Trip", foreign_key: "end_station_id"
  validates :name, presence: true, uniqueness: true
  validates_presence_of :dock_count, :city, :installation_date

  def self.sort_by_id
    all.order(:id)
  end

  def sum_starting_trips
    start_stations.length
  end

  def sum_ending_trips
    end_stations.length
  end

  # Ask about returning an object from the query.
  def frequent_destination_station
    start_stations.group(:end_station_id).order("count_all desc").count.first
  end

  def frequent_origination_station
    end_stations.group(:start_station_id).order("count_all DESC").count.first
  end

  def date_with_most_trip_starts
    start_stations.group(:start_date).order("count_all DESC").count.first[0]
  end

  def most_freq_zip_codes
    start_stations.group(:zip_code).order("count_all DESC").count.first[0]
  end

  def most_freq_bike_id
    start_stations.group(:bike_id).order("count_all DESC").count.first[0]
  end

  def self.oldest_station
    order("installation_date ASC").first
  end

  def self.newest_station
    order("installation_date DESC").first
  end

  def self.most_bikes
    order("dock_count DESC").first
  end

  def self.least_bikes
    order("dock_count ASC").first
  end

  def self.average_bikes
    average(:dock_count).round
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController
  def show
    station = Station.friendly.find(params[:id])
    redirect_to station_path(station)
  end

  def new
    @station = Station.new
  end

  def create
    params[:station][:installation_date] = "#{params[:station]["installation_date(2i)"]}/#{params[:station]["installation_date(3i)"]}/#{params[:station]["installation_date(1i)"]}"
    station = Station.new(station_params)
    if station.save
      flash[:success] = "You have created a new station called #{station.name}!"
    end
    redirect_to station_path(station)
  end

  def edit
    @station = Station.friendly.find(params[:id])
  end

  def update
    station = Station.friendly.find(params[:id])
    params[:station][:installation_date] = "#{params[:station]["installation_date(2i)"]}/#{params[:station]["installation_date(3i)"]}/#{params[:station]["installation_date(1i)"]}"
    if station.update(station_params)
      flash[:success] = "You have updated #{station.name} station!"
    end
    redirect_to station_path(station)
  end

  def destroy
    station = Station.friendly.find(params[:id])
    trips = Trip.where("end_station_id=? OR start_station_id=?", station.id, station.id)
    trips.each do |trip|
      trip.destroy
    end
    station.destroy
    flash[:success] = "#{station.name} was successfully deleted!"
    redirect_to stations_path
  end

  private

  def station_params
    params.require(:station).permit(:city, :installation_date, :name, :dock_count)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def show
    @station = Station.friendly.find(params[:id])
    if @station.start_stations != [] || @station.end_stations != []
      @frequent_destination = Station.find(@station.frequent_destination_station[0]).name
      @frequent_origination = Station.find(@station.frequent_origination_station[0]).name
    end
  end

  def index
    @stations = Station.sort_by_id
  end
end

app/views/stations/index.html.slim
h1 style="text-align: center;" 
  'All Stations
- if current_admin?
  div class="col-md-12 text-center" style="width: 100%; margin-bottom: 15px;"
    = button_to 'Create a New Station', new_admin_station_path, method: :get, class: "btn btn-primary", style: "justification: center;"
table class="table table-striped table-bordered"
  thead
    tr
      th scope="col"
        h3
          'Station Name
      th scope="col"
        h3
          'Dock Count
      th scope="col"
        h3
          'City
      th scope="col"
        h3
          'Installation Date
      - if current_admin?
        th
          h3
            'Admin Actions
  tbody
    - @stations.each do |station|
      tr
        th
          p
            = link_to "#{station.name}", station_path(station)
        th
          p
            = station.dock_count
        th
          p
            = station.city
        th
          p
            = station.installation_date.strftime("%A, %m/%d/%Y")
        - if current_admin?
          th style="text-align: center;"
            = button_to 'Delete Station', admin_station_path(station), method: :delete, class: "btn btn-primary", style: "width: 85%;"
            = button_to 'Edit Station', edit_admin_station_path(station), method: :get, class: "btn btn-primary", style: "width: 85%; margin-top: 8px;"

app/views/stations/show.html.slim
div class="well" style="text-align: center;"
  h2
    'Station Name:
    = @station.name
div class="col-lg-4"
div class="col-lg-4"
  div class="well well-sm" style="text-align: center;"
    h5
      'Dock Count:
      = @station.dock_count
  div class="well well-sm" style="text-align: center;"
    h5
      'City:
      = @station.city
  div class="well well-sm" style="text-align: center;"
    h5
      'Installation Date:
      = @station.installation_date.strftime("%A, %m/%d/%Y")
- if current_admin?
  = link_to 'Edit This Station', edit_admin_station_path(@station), class: 'btn btn-primary'
  = link_to 'Delete This Station', admin_station_path(@station), method: :delete, class: 'btn btn-primary'
- if @station.start_stations != [] && @station.end_stations != []
  div class="col-lg-4" style="height: 225px;"
  h1 Station Statistics
  div class="card-columns" style="text-align:center; column-count: 3;"
    div class="card"  
      div class="card-body"
        h3 class="card-title" 
          'Number of Trips Starting at This Station:
        h5 class="card-text"
          = @station.sum_starting_trips
    div class="card"  
      div class="card-body"
        h3 class="card-title" 
          'Number of Trips Ending at This Station:
        h5 class="card-text"
          = @station.sum_ending_trips
    div class="card"  
      div class="card-body"
        h3 class="card-title" 
          'Date With the Highest Number of Starting Trips:
        h5 class="card-text"
          = @station.date_with_most_trip_starts.strftime("%A, %m/%d/%Y")
    div class="card"  
      div class="card-body"
        h3 class="card-title" 
          'Most Frequent Destination Station from Here:
        h5 class="card-text"
          = @frequent_destination
    div class="card"  
      div class="card-body"
        h3 class="card-title" 
          'Most Frequent Origination Station for Trips to Here:
        h5 class="card-text"
          = @frequent_origination
    div class="card"  
      div class="card-body"
        h3 class="card-title" 
          'Most Frequent Zip Codes for Users Starting Trips at this Station:
        h5 class="card-text"
          = @station.most_freq_zip_codes
    div class="card"  
      div class="card-body"
        h3 class="card-title" 
          'Most Frequent Bike ID Starting Trips Here:
        h5 class="card-text"
          = @station.most_freq_bike_id