config/routes.rb
Rails.application.routes.draw do
  root "homepages#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: 'users#show'

  get '/admin/dashboard', to: 'admin/dashboards#show'
  get '/admin/bike-shop/new', to: 'admin/items#new'

  resources :users, only: [:new, :create, :edit, :update]

  get "/:station-name", to: redirect("/%{station-name}")
  resources :stations, only: [:index, :show]

  resources :trips, only: [:show, :index]

  resources :items, only: [:show]
  get '/bike-shop', to: 'items#index'

  resources :orders, only: [:new, :create, :show]

  namespace :admin do
    resources :stations, only: [:new, :create, :destroy, :edit, :update]
    resources :trips
    resources :items
    resources :orders, only: [:update]
    get '/bike-shop', to: 'items#index'
    get '/dashboard', to: 'dashboards#show'
  end

  get '/cart', to: "cart#index"
  patch '/bike-shop', to: "cart#update"
  delete '/bike-shop', to: 'cart#destroy'

  get '/stations-dashboard', to: 'homepages#show'
  get '/trips-dashboard', to: 'homepages#show'

  match '*path', to: 'unknowns#index', via: :all
end

app/views/partials/_item.html.slim
div class="container-fluid" style="width: 85%;"
    = form_for [:admin, @item], html: { class: "needs-validation", style: "width: 85%;"} do |f|
      = f.label :title
      = f.text_field :title, class: "form-control", required: true

      = f.label :price
      = f.number_field :price, :step => 0.01, class: 'form-control', required: true

      = f.label :image
      = f.text_field :image, class: 'form-control'

      = f.label :description
      = f.text_field :description, class: 'form-control', required: true

      = f.submit

app/views/partials/_navbar.html.slim
nav class="navbar navbar-default"
  div class="container-fluid" id="navbar-container-1"
    div class="navbar-header"
      = link_to 'Bike Share', root_path, class: "navbar-brand pull-left"

    ul class="nav navbar-nav"
      li class="#{current_class?(root_path) || current_class?(new_user_path)}"
        = link_to 'Home', root_path
      - if current_user && !current_admin?
        li class="#{current_class?(dashboard_path)}"
          = link_to 'Profile', dashboard_path
      - elsif current_admin?
        li class="#{current_class?(admin_dashboard_path)}"
          = link_to 'Admin Dashboard', admin_dashboard_path
      li class="#{current_class?(trips_path) || current_class?(trip_path(@trip))}"
        = link_to 'Trips', trips_path
      li class="#{current_class?(stations_path) || current_class?(station_path(@station))}"
        = link_to 'Stations', stations_path
      li class="#{current_class?(bike_shop_path)}"
        = link_to 'Bike Shop', bike_shop_path
      li class="#{current_class?(stations_dashboard_path)}"
        = link_to 'Station Dashboard', stations_dashboard_path
      li class="#{current_class?(trips_dashboard_path)}"
        = link_to 'Trip Dashboard', trips_dashboard_path
    ul class="nav navbar-nav navbar-right"
      - if current_user && !current_admin?
        li style="margin-top:17px;"
          ' Logged in as
          = current_user.username
      - elsif current_admin?
        li style="margin-top:17px;"
          'Logged in as Admin User:
          = current_user.username
      li
        = link_to cart_path do
          - if session[:shopping_cart].values.sum == 0
            span class="glyphicon glyphicon-shopping-cart"
              '  Cart - Empty
          -else
            span class="glyphicon glyphicon-shopping-cart"
              '  Cart - 
              = session[:shopping_cart].values.sum
      - if current_user
        li
          = link_to 'Log Out', logout_path, method: :delete
      - else
        li
          = link_to 'Log In', login_path

app/views/partials/_session_new.html.slim
= form_for(:session, url: login_path) do |f|
  = f.label :email
  = f.email_field :email, class: 'form-control'

  = f.label :password
  = f.password_field :password, class: 'form-control'

  = f.submit 'Log In', class: 'btn btn-primary', style: 'margin-top:15px;'

app/views/partials/_station.html.slim
div class="container-fluid" style="width: 85%;"
  = form_for([:admin, @station], html: { class: "needs-validation" }) do |form|
    div class="form-row"
      div class="col-md-4 mb-3"
        = form.label :name
        = form.text_field :name, class: "form-control", placeholder: "Station Name", required: true

      div class="col-md-4 mb-3"
        = form.label :city
        = form.text_field :city, class: "form-control", placeholder: "City", required: true

    div class="form-row" style="margin-top: 15px;"
      div class="col-md-4 mb-3" 
        = form.label :dock_count
        = form.number_field :dock_count, class: "form-control", placeholder: "Dock Count", required: true
    
      div class="col-md-4 mb-3" style="margin-top: 25px;"
        = form.label :installation_date
        = form.date_select :installation_date, class: "form-control" , required: true

    div class="form-row" style="justify-content: center; margin-top: 35px; margin-right: 45px;"
      div class="actions"
        = form.submit

app/views/partials/_trip.html.slim
div class="container-fluid" style="width: 85%;"
  = form_for([:admin, @trip], html: { class: "needs-validation" }) do |f|
    div class="form-row"
      div class="col-md-4 mb-3"
        = f.label :duration
        = f.text_field :duration, class: "form-control", required: true
      div class="col-md-4 mb-3" style="margin-top: 25px;"
        = f.label :start_date
        = f.date_select :start_date, :prompt => {:year => 'Select Year', :month => 'Select Month', :day => 'Select Day'}
      div class="col-md-4 mb-3" style="margin-top: 25px;"
        = f.label :end_date
        = f.date_select :end_date, :prompt => {:year => 'Select Year', :month => 'Select Month', :day => 'Select Day'}
    div class="form-row"
      div class="col-md-4 mb-3"
        = f.label :bike_id
        = f.text_field :bike_id, class: "form-control", required: true
      div class="col-md-4 mb-3"
        = f.label :subscription_type
        = f.text_field :subscription_type, class: "form-control", required: true
      div class="col-md-4 mb-3"
        = f.label :zip_code
        = f.text_field :zip_code, class: "form-control", required: true
    div class="form-row" style="justify-content:center;"
      div class="col-md-4 mb-3" style="margin-top: 25px;"
        = f.label :start_station_id
        = f.collection_select :start_station_id, Station.all, :id, :name
      div class="col-md-4 mb-3" style="margin-top: 25px;"
        = f.label :end_station_id
        = f.collection_select :end_station_id, Station.all, :id, :name

        = f.submit class: 'btn btn-primary'

app/views/partials/_users.html.slim
div class="container-fluid" style="width: 85%;"
  = form_for(@user, html: { class: "needs-validation"}) do |form|
    div class="form-row"
      div class="col-md-4 mb-3"
        = form.label :first_name
        = form.text_field :first_name, class: "form-control", placeholder: "First Name", id: "validationDefault01", required: true
        required

      div class="col-md-4 mb-3"
        = form.label :last_name
        = form.text_field :last_name, class: "form-control", placeholder: "Last Name", id: "validationDefault02", required: true

      div class="col-md-4 mb-3"
        = form.label :email
        = form.email_field :username, class: "form-control", placeholder: "Email", id: "validationDefaultUsername", required: true
    
    div class="form-row"
      div style="width: 100%;"
        = form.label :address
        = form.text_field :address, class: "form-control", placeholder: "Full address with city/state", id: "validationDefaultAddress", required: true

    div class="form-row" style="justify-content: center; margin-top: 15px;"
      div class="col-md-4 mb-3"
        = form.label :password
        = form.password_field :password, class: "form-control", placeholder: "Password", id: "validationDefaultPassword", required: true

      div class="col-md-4 mb-3"
        = form.label :password_confirmation
        = form.password_field :password_confirmation, class: "form-control", placeholder: "Password", id: "validationDefaultPasswordConfirmation", required: true

    div class="form-row" style="justify-content: center; margin-top: 35px; margin-right: 45px;"
      div class="actions"
        = form.submit