config/routes.rb
Rails.application.routes.draw do
  root "homepages#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: 'users#show'

  get '/admin/dashboard', to: 'admin/dashboards#show'
  get '/admin/bike-shop/new', to: 'admin/items#new'

  resources :users, only: [:new, :create, :edit, :update]

  get "/:station-name", to: redirect("/%{station-name}")
  resources :stations, only: [:index, :show]

  resources :trips, only: [:show, :index]

  resources :items, only: [:show]
  get '/bike-shop', to: 'items#index'

  resources :orders, only: [:new, :create, :show]

  namespace :admin do
    resources :stations, only: [:new, :create, :destroy, :edit, :update]
    resources :trips
    resources :items
    resources :orders, only: [:update]
    get '/bike-shop', to: 'items#index'
    get '/dashboard', to: 'dashboards#show'
  end

  get '/cart', to: "cart#index"
  patch '/bike-shop', to: "cart#update"
  delete '/bike-shop', to: 'cart#destroy'

  get '/stations-dashboard', to: 'homepages#show'
  get '/trips-dashboard', to: 'homepages#show'

  match '*path', to: 'unknowns#index', via: :all
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :item_orders
  has_many :items, through: :item_orders
  validates_presence_of :status

  def self.status_count(status)
    where(status: status).count
  end

  def self.ordered
    where(status: 'ordered')
  end

  def self.cancelled
    where(status: 'cancelled')
  end

  def self.completed
    where(status: 'completed')
  end

  def self.paid
    where(status: 'paid')
  end 
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def update
    params["order"]["status"] = (params["order"]["status"])
    order = Order.find(params[:id])
    if order.update(order_params)
      flash[:success] = "You have updated the order status!"
    end
    redirect_back(fallback_location: admin_dashboard_path)
  end


  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    if @order.nil?
      render file: 'public/404'
    else
      @items = @order.item_orders.map { |item_order| { Item.find(item_order.item_id) => item_order.quantity } }
      @order_total = @items.map { |item_hash| item_hash.keys.first.price * item_hash.values.first }.sum
      @purchaser = @order.user
    end
  end

  def create
    order = current_user.orders.create(order_params)
    params[:items].each do |item_id, quantity|
      order.item_orders.create(item_id: item_id, quantity: quantity)
    end
    if current_admin?
      session[:flash_notice] = params[:flash_notice]
      session[:shopping_cart] = nil
      redirect_to admin_dashboard_path
      return
    else
      session[:flash_notice] = params[:flash_notice]
      session[:shopping_cart] = nil
      redirect_to dashboard_path
      return
    end
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/views/admin/orders/show.html.slim
h1
  'Order ID:
  = @order.id

div class="container-fluid"
  div class="row"
    - @items.each do |item_hash|
      div class="col-md-3" style="text-align: center;"
        ul class="item-index-list" style="list-style-type: none;"
          li
            'Item Name:
            = link_to "#{item_hash.keys.first.title}", item_path(item_hash.keys.first)
          li
            'Item Quantity:
            = item_hash.values.first
          li
            'Item Subtotal: $
            = '%.2f' % (item_hash.keys.first.price * item_hash.values.first)
h2
  'Total Number of Items
  = @items.map { |ele| ele.values.first }.sum
h2
  'Order Total: $
  = '%.2f' % @order_total
h2
  'Order Status:
  = @order.status
h2
  'Order Submitted:
  = @order.created_at.strftime("%A, %m/%d/%Y")
h2
  - if @order.status == 'completed'
  'Order was shipped on
    = @order.updated_at
  - elsif @order.status == 'cancelled'
    'Order was cancelled on
      = @order.updated_at